In [222]:
# import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print("importing is done")

importing is done


In [223]:
#loading the dataset
df=pd.read_csv('data.csv')

In [224]:
#summarizing the dataset
df

AnimalName                        symptoms1             symptoms2  \
0          Dog                            Fever              Diarrhea   
1          Dog                            Fever              Diarrhea   
2          Dog                            Fever              Diarrhea   
3          Dog                            Fever  Difficulty breathing   
4          Dog                            Fever              Diarrhea   
..         ...                              ...                   ...   
866  Buffaloes                            Fever  Difficulty breathing   
867  Buffaloes                            Fever     Loss of  appetite   
868  Buffaloes      Lesions in the nasal cavity       Lesions on nose   
869  Buffaloes                        Hair loss              Dandruff   
870  Buffaloes  Greenish-yellow nasal discharge  Lack of pigmentation   

               symptoms3             symptoms4           symptoms5 Dangerous  
0               Vomiting           Weight loss         Dehydration       Yes  
1               Coughing             Tiredness               Pains       Yes  
2               Coughing              Vomiting            Anorexia       Yes  
3               Coughing              Lethargy            Sneezing       Yes  
4               Coughing              Lethargy            Blue Eye       Yes  
..                   ...                   ...                 ...       ...  
866        Poor Appetite   Eye and Skin change  Unable to exercise       Yes  
867  Lession on the skin              Lethargy          Joint Pain       Yes  
868             Vomiting       Noisy Breathing     Lesions on nose       Yes  
869             Vomiting  Crusting of the skin      Ulcerated skin       Yes  
870             Vomiting              Lethargy        Pain on face       Yes  

[871 rows x 7 columns]

In [225]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 871 entries, 0 to 870
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   AnimalName  871 non-null    object
 1   symptoms1   871 non-null    object
 2   symptoms2   871 non-null    object
 3   symptoms3   871 non-null    object
 4   symptoms4   871 non-null    object
 5   symptoms5   871 non-null    object
 6   Dangerous   869 non-null    object
dtypes: object(7)
memory usage: 47.8+ KB


In [226]:
df.describe()

AnimalName symptoms1 symptoms2 symptoms3    symptoms4 symptoms5  \
count         871       871       871       871          871       871   
unique         46       232       230       229          217       203   
top     Buffaloes     Fever  Diarrhea  Coughing  Weight loss     Pains   
freq          129       257       119        95          117        99   

       Dangerous  
count        869  
unique         2  
top          Yes  
freq         849

In [227]:
df.dtypes

AnimalName    object
symptoms1     object
symptoms2     object
symptoms3     object
symptoms4     object
symptoms5     object
Dangerous     object
dtype: object

In [228]:
# pre-processing the dataset
# Now we check if any Null value is present or not 
df.isnull().sum()

AnimalName    0
symptoms1     0
symptoms2     0
symptoms3     0
symptoms4     0
symptoms5     0
Dangerous     2
dtype: int64

In [229]:
# we use max fucntion to find null values
df.isnull().sum().max()

2

In [230]:
# here we can see that last column has 2 nunll values in it
# Replace null values with 'Unknown'
df.fillna('Unknown', inplace=True)

In [231]:
# we use max fucntion to find null values
df.isnull().sum().max()

0

In [232]:
# we have treated the null values and finally our dataset doesnot have any null values.

In [233]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 871 entries, 0 to 870
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   AnimalName  871 non-null    object
 1   symptoms1   871 non-null    object
 2   symptoms2   871 non-null    object
 3   symptoms3   871 non-null    object
 4   symptoms4   871 non-null    object
 5   symptoms5   871 non-null    object
 6   Dangerous   871 non-null    object
dtypes: object(7)
memory usage: 47.8+ KB


In [234]:
# we import new libraries to encode the Gender column
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder

In [235]:
label = LabelEncoder()
label

LabelEncoder()

In [236]:
# Performing Label Encoding for "AnimalName Column"
label.fit_transform(df.AnimalName)
df['AnimalName']=label.fit_transform(df.AnimalName)
df.AnimalName

0      6
1      6
2      6
3      6
4      6
      ..
866    2
867    2
868    2
869    2
870    2
Name: AnimalName, Length: 871, dtype: int32

In [237]:
# Performing Label Encoding for "symptoms1 Column"
label.fit_transform(df.symptoms1)
df['symptoms1']=label.fit_transform(df.symptoms1)
df.symptoms1

0      63
1      63
2      63
3      63
4      63
       ..
866    63
867    63
868    97
869    77
870    75
Name: symptoms1, Length: 871, dtype: int32

In [238]:
# Performing Label Encoding for "symptoms2 Column"
label.fit_transform(df.symptoms2)
df['symptoms2']=label.fit_transform(df.symptoms2)
df.symptoms2

0      31
1      31
2      31
3      34
4      31
       ..
866    34
867    95
868    90
869    26
870    84
Name: symptoms2, Length: 871, dtype: int32

In [239]:
# Performing Label Encoding for "symptoms3 Column"
label.fit_transform(df.symptoms3)
df['symptoms3']=label.fit_transform(df.symptoms3)
df.symptoms3

0      179
1       31
2       31
3       31
4       31
      ... 
866    115
867     88
868    179
869    179
870    179
Name: symptoms3, Length: 871, dtype: int32

In [240]:
# Performing Label Encoding for "symptoms4 Column"
label.fit_transform(df.symptoms4)
df['symptoms4']=label.fit_transform(df.symptoms4)
df.symptoms4

0      182
1      165
2      173
3       87
4       87
      ... 
866     53
867     87
868    107
869     27
870     87
Name: symptoms4, Length: 871, dtype: int32

In [241]:
# Performing Label Encoding for "symptoms5 Column"
label.fit_transform(df.symptoms5)
df['symptoms5']=label.fit_transform(df.symptoms5)
df.symptoms5

0       32
1      113
2        8
3      142
4       21
      ... 
866    160
867     78
868     82
869    159
870    111
Name: symptoms5, Length: 871, dtype: int32

In [242]:
# Performing Label Encoding for "Dangerous Column"
label.fit_transform(df.Dangerous)
df['Dangerous']=label.fit_transform(df.Dangerous)
df.Dangerous

0      2
1      2
2      2
3      2
4      2
      ..
866    2
867    2
868    2
869    2
870    2
Name: Dangerous, Length: 871, dtype: int32

In [243]:
type(df['AnimalName'])

pandas.core.series.Series

In [244]:
type(df['symptoms1'])

pandas.core.series.Series

In [245]:
type(df['symptoms2'])

pandas.core.series.Series

In [246]:
type(df['symptoms3'])

pandas.core.series.Series

In [247]:
type(df['symptoms4'])

pandas.core.series.Series

In [248]:
type(df['symptoms5'])

pandas.core.series.Series

In [249]:
type(df['Dangerous'])

pandas.core.series.Series

In [250]:
# this is our cleaned dataset
df

AnimalName  symptoms1  symptoms2  symptoms3  symptoms4  symptoms5  \
0             6         63         31        179        182         32   
1             6         63         31         31        165        113   
2             6         63         31         31        173          8   
3             6         63         34         31         87        142   
4             6         63         31         31         87         21   
..          ...        ...        ...        ...        ...        ...   
866           2         63         34        115         53        160   
867           2         63         95         88         87         78   
868           2         97         90        179        107         82   
869           2         77         26        179         27        159   
870           2         75         84        179         87        111   

     Dangerous  
0            2  
1            2  
2            2  
3            2  
4            2  
..         ...  
866          2  
867          2  
868          2  
869          2  
870          2  

[871 rows x 7 columns]

In [251]:
# create input data as x and create output data as y
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [252]:
x.shape

(871, 6)

In [253]:
y.shape

(871,)

In [254]:
# import additionl required libraries
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score, classification_report
print("importing is done")

importing is done


In [255]:
x, y.shape

(array([[  6,  63,  31, 179, 182,  32],
        [  6,  63,  31,  31, 165, 113],
        [  6,  63,  31,  31, 173,   8],
        ...,
        [  2,  97,  90, 179, 107,  82],
        [  2,  77,  26, 179,  27, 159],
        [  2,  75,  84, 179,  87, 111]]),
 (871,))

In [256]:
# now we give training and testing data by split method
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2,random_state=70)

In [257]:
x_train.shape

(696, 6)

In [258]:
x_test.shape

(175, 6)

In [259]:
y_train.shape

(696,)

In [260]:
y_test.shape

(175,)

In [261]:
#now we create a model for this dataset
model_data=AdaBoostClassifier()
model_data

AdaBoostClassifier()

In [262]:
# now we train our model
model_data.fit(x_train, y_train)

AdaBoostClassifier()

In [263]:
# now our model is trained so we put it to test
y_data = model_data.predict(x_test)
y_data

array([2, 0, 0, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2,
       0, 2, 2, 0, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0, 0, 2, 0, 2,
       2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2,
       0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2,
       2, 2, 2, 2, 2, 2, 2, 0, 2, 0, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2,
       0, 2, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 2, 2, 0, 2, 0, 2, 2, 2, 2])

In [264]:
# to check accuracy we need to import additional library
from sklearn.metrics import accuracy_score, classification_report

In [265]:
# now we check for accuracy of test data vs training data
accuracy = accuracy_score(y_test, y_data)
np.round(accuracy,2)*100

78.0

In [270]:
# we get 78% accuracy by keeping split as 80/20.
# if we keep split as 70/30
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.3,random_state=70)
model_data = AdaBoostClassifier()
model_data.fit(x_train, y_train)
y_data=model_k.predict(x_test)
accuracy = accuracy_score(y_test, y_data)
np.round(accuracy,2)*100

94.0

In [271]:
# Predicting the output of single test data using our trained model
y_test

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2])

In [272]:
x_test.shape

(262, 6)

In [273]:
x_test[2]

array([ 12,  17,  31, 179,  87,  13])

In [275]:
x_test[2].shape

(6,)

In [276]:
x_test[2].reshape(1,6)

array([[ 12,  17,  31, 179,  87,  13]])

In [277]:
x_test[2].reshape(1,6).shape

(1, 6)

In [278]:
model_data.predict(x_test[2].reshape(1,6))

array([2])