In [115]:
# import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print("importing is done")

importing is done


In [116]:
#load the dataset
df=pd.read_csv('bmi.csv')

In [117]:
# summarizing the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Gender  500 non-null    object
 1   Height  500 non-null    int64 
 2   Weight  500 non-null    int64 
 3   Index   500 non-null    int64 
dtypes: int64(3), object(1)
memory usage: 15.8+ KB


In [118]:
df.describe()

Height      Weight       Index
count  500.000000  500.000000  500.000000
mean   169.944000  106.000000    3.748000
std     16.375261   32.382607    1.355053
min    140.000000   50.000000    0.000000
25%    156.000000   80.000000    3.000000
50%    170.500000  106.000000    4.000000
75%    184.000000  136.000000    5.000000
max    199.000000  160.000000    5.000000

In [119]:
len(df)

500

In [120]:
df.dtypes

Gender    object
Height     int64
Weight     int64
Index      int64
dtype: object

In [121]:
# pre-processing the dataset
# Now we check if any Null value is present or not 
df.isnull().sum()

Gender    0
Height    0
Weight    0
Index     0
dtype: int64

In [122]:
# we use max fucntion to find null values
df.isnull().sum().max()

0

In [123]:
# from this dataset we will have to perform label encoding on gender column 
df

Gender  Height  Weight  Index
0      Male     174      96      4
1      Male     189      87      2
2    Female     185     110      4
3    Female     195     104      3
4      Male     149      61      3
..      ...     ...     ...    ...
495  Female     150     153      5
496  Female     184     121      4
497  Female     141     136      5
498    Male     150      95      5
499    Male     173     131      5

[500 rows x 4 columns]

In [124]:
# we import new libraries to encode the Gender column
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder

In [125]:
label = LabelEncoder()
label

LabelEncoder()

In [126]:
# Performing Label Encoding for "Gender Column"
label.fit_transform(df.Gender)
df['Gender']=label.fit_transform(df.Gender)
df.Gender


0      1
1      1
2      0
3      0
4      1
      ..
495    0
496    0
497    0
498    1
499    1
Name: Gender, Length: 500, dtype: int32

In [127]:
#we have succcessfully encoded the Gender column.
df

Gender  Height  Weight  Index
0         1     174      96      4
1         1     189      87      2
2         0     185     110      4
3         0     195     104      3
4         1     149      61      3
..      ...     ...     ...    ...
495       0     150     153      5
496       0     184     121      4
497       0     141     136      5
498       1     150      95      5
499       1     173     131      5

[500 rows x 4 columns]

In [152]:
# create x and y varibales
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [153]:
# we check x variable
x

array([[  1, 174,  96],
       [  1, 189,  87],
       [  0, 185, 110],
       ...,
       [  0, 141, 136],
       [  1, 150,  95],
       [  1, 173, 131]], dtype=int64)

In [154]:
# we check y variable
y

array([4, 2, 4, 3, 3, 3, 5, 5, 3, 4, 2, 4, 3, 2, 2, 5, 5, 5, 5, 5, 5, 5,
       4, 5, 2, 3, 3, 1, 5, 5, 5, 1, 1, 5, 5, 4, 3, 4, 5, 2, 4, 5, 2, 5,
       4, 2, 4, 4, 3, 5, 5, 1, 5, 4, 4, 3, 4, 5, 3, 5, 0, 5, 0, 2, 5, 5,
       4, 2, 4, 4, 2, 4, 5, 2, 3, 4, 4, 4, 4, 0, 3, 5, 3, 4, 5, 0, 5, 5,
       5, 5, 5, 3, 3, 2, 4, 5, 4, 5, 1, 0, 4, 5, 5, 4, 4, 4, 5, 5, 4, 3,
       4, 5, 4, 2, 4, 3, 2, 5, 5, 5, 4, 4, 4, 5, 5, 4, 4, 4, 5, 2, 5, 2,
       5, 4, 5, 5, 5, 3, 5, 5, 2, 4, 5, 5, 5, 4, 3, 5, 3, 3, 0, 3, 3, 5,
       5, 4, 3, 5, 3, 4, 2, 2, 3, 5, 4, 2, 4, 5, 3, 2, 4, 5, 5, 4, 4, 4,
       4, 3, 5, 3, 3, 4, 4, 2, 3, 3, 5, 3, 5, 4, 5, 5, 4, 5, 5, 5, 4, 4,
       5, 5, 1, 3, 4, 4, 5, 4, 5, 4, 3, 4, 4, 5, 5, 5, 0, 5, 5, 5, 5, 5,
       2, 5, 4, 5, 0, 5, 3, 4, 5, 5, 4, 2, 3, 3, 4, 3, 5, 5, 2, 5, 3, 2,
       1, 5, 0, 5, 3, 5, 3, 4, 3, 5, 5, 5, 5, 2, 4, 5, 5, 4, 5, 5, 5, 2,
       4, 5, 5, 5, 5, 1, 5, 5, 4, 0, 3, 3, 4, 2, 3, 1, 1, 5, 5, 4, 4, 4,
       4, 5, 2, 5, 4, 3, 3, 4, 5, 5, 2, 4, 3, 4, 5,

In [155]:
# # import additionl required libraries
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score, classification_report
print("importing is done")

importing is done


In [156]:
 #now we create training and testing data for our model
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2, random_state=4)

In [157]:
# now we check our testing and training variables
x_train.shape,x_test.shape, y_train.shape, y_test.shape

((400, 3), (100, 3), (400,), (100,))

In [158]:
#create a model
model_bmi = AdaBoostClassifier()
model_bmi

AdaBoostClassifier()

In [159]:
# we train our model
model_bmi.fit(x_train, y_train)

AdaBoostClassifier()

In [160]:
# Now testing new Model prediction by providing Test Data set
y_bmi=model_bmi.predict(x_test)

In [161]:
# this is our variable which has learned the test data
y_bmi

array([4, 3, 5, 5, 2, 5, 3, 5, 5, 3, 5, 3, 5, 5, 5, 4, 5, 2, 5, 5, 5, 2,
       5, 4, 4, 4, 4, 4, 2, 4, 3, 4, 5, 5, 3, 4, 4, 5, 4, 2, 4, 4, 5, 5,
       4, 3, 3, 4, 5, 5, 4, 3, 2, 2, 5, 5, 4, 5, 5, 5, 5, 5, 4, 3, 4, 4,
       4, 4, 5, 5, 5, 3, 4, 3, 4, 3, 4, 2, 5, 2, 5, 4, 5, 5, 5, 4, 2, 5,
       5, 5, 4, 4, 3, 4, 2, 2, 4, 4, 4, 4], dtype=int64)

In [162]:
# to check accuracy we need to import additional library
from sklearn.metrics import accuracy_score, classification_report

In [163]:
# Compare predictions with testing data given
# this will only give accuracy
accuracy = accuracy_score(y_test, y_bmi)
np.round(accuracy,2)*100

57.99999999999999

In [164]:
# we get 58% accuracy by keeping split as 80/20.
# if we keep split as 70/30
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.30,random_state=4)
model_bmi = AdaBoostClassifier()
model_bmi.fit(x_train, y_train)
y_bmi=model_bmi.predict(x_test)
accuracy = accuracy_score(y_test, y_bmi)
np.round(accuracy,2)*100

46.0

In [165]:
# Predicting the output of single test data using our trained model
y_test

array([4, 3, 5, 4, 2, 5, 3, 5, 5, 4, 5, 2, 5, 5, 5, 5, 5, 3, 5, 4, 5, 2,
       5, 5, 3, 2, 3, 2, 1, 2, 3, 4, 5, 5, 2, 5, 4, 5, 5, 2, 3, 4, 5, 5,
       5, 2, 2, 5, 5, 5, 5, 2, 0, 2, 5, 5, 4, 5, 5, 4, 5, 5, 4, 4, 5, 2,
       4, 5, 5, 5, 5, 2, 5, 2, 4, 2, 4, 2, 5, 1, 5, 4, 5, 4, 5, 3, 3, 5,
       5, 4, 4, 5, 3, 4, 2, 2, 4, 3, 3, 3, 4, 4, 2, 4, 4, 4, 5, 5, 4, 1,
       5, 4, 5, 2, 5, 4, 5, 4, 2, 0, 5, 2, 3, 5, 2, 5, 4, 5, 5, 3, 4, 1,
       4, 5, 1, 5, 4, 4, 4, 5, 1, 3, 5, 5, 0, 4, 5, 2, 5, 4], dtype=int64)

In [177]:
x_test.shape

(150, 3)

In [167]:
x_test[4]

array([  0, 153,  51], dtype=int64)

In [171]:
x_test[4].shape

(3,)

In [172]:
x_test[4].reshape(1,3)

array([[  0, 153,  51]], dtype=int64)

In [173]:
x_test[4].reshape(1,3).shape

(1, 3)

In [176]:
model_bmi.predict(x_test[4].reshape(1,3))

array([2], dtype=int64)