In [550]:
# import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print("importing is done")

importing is done


In [551]:
#load the dataset
df=pd.read_csv('brain_stroke.csv')

In [552]:
#summarizing the dataset
df

gender   age  hypertension  heart_disease ever_married      work_type  \
0       Male  67.0             0              1          Yes        Private   
1       Male  80.0             0              1          Yes        Private   
2     Female  49.0             0              0          Yes        Private   
3     Female  79.0             1              0          Yes  Self-employed   
4       Male  81.0             0              0          Yes        Private   
...      ...   ...           ...            ...          ...            ...   
4976    Male  41.0             0              0           No        Private   
4977    Male  40.0             0              0          Yes        Private   
4978  Female  45.0             1              0          Yes       Govt_job   
4979    Male  40.0             0              0          Yes        Private   
4980  Female  80.0             1              0          Yes        Private   

     Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
0             Urban             228.69  36.6  formerly smoked       1  
1             Rural             105.92  32.5     never smoked       1  
2             Urban             171.23  34.4           smokes       1  
3             Rural             174.12  24.0     never smoked       1  
4             Urban             186.21  29.0  formerly smoked       1  
...             ...                ...   ...              ...     ...  
4976          Rural              70.15  29.8  formerly smoked       0  
4977          Urban             191.15  31.1           smokes       0  
4978          Rural              95.02  31.8           smokes       0  
4979          Rural              83.94  30.0           smokes       0  
4980          Urban              83.75  29.1     never smoked       0  

[4981 rows x 11 columns]

In [553]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4981 entries, 0 to 4980
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   gender             4981 non-null   object 
 1   age                4981 non-null   float64
 2   hypertension       4981 non-null   int64  
 3   heart_disease      4981 non-null   int64  
 4   ever_married       4981 non-null   object 
 5   work_type          4981 non-null   object 
 6   Residence_type     4981 non-null   object 
 7   avg_glucose_level  4981 non-null   float64
 8   bmi                4981 non-null   float64
 9   smoking_status     4981 non-null   object 
 10  stroke             4981 non-null   int64  
dtypes: float64(3), int64(3), object(5)
memory usage: 428.2+ KB


In [554]:
df.dtypes

gender                object
age                  float64
hypertension           int64
heart_disease          int64
ever_married          object
work_type             object
Residence_type        object
avg_glucose_level    float64
bmi                  float64
smoking_status        object
stroke                 int64
dtype: object

In [555]:
df.describe()

age  hypertension  heart_disease  avg_glucose_level  \
count  4981.000000   4981.000000    4981.000000        4981.000000   
mean     43.419859      0.096165       0.055210         105.943562   
std      22.662755      0.294848       0.228412          45.075373   
min       0.080000      0.000000       0.000000          55.120000   
25%      25.000000      0.000000       0.000000          77.230000   
50%      45.000000      0.000000       0.000000          91.850000   
75%      61.000000      0.000000       0.000000         113.860000   
max      82.000000      1.000000       1.000000         271.740000   

               bmi       stroke  
count  4981.000000  4981.000000  
mean     28.498173     0.049789  
std       6.790464     0.217531  
min      14.000000     0.000000  
25%      23.700000     0.000000  
50%      28.100000     0.000000  
75%      32.600000     0.000000  
max      48.900000     1.000000

In [556]:
# pre-processing the dataset
# Now we check if any Null value is present or not 
df.isnull().sum()

gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

In [557]:
# we use max fucntion to find null values
df.isnull().sum().max()

0

In [558]:
df

gender   age  hypertension  heart_disease ever_married      work_type  \
0       Male  67.0             0              1          Yes        Private   
1       Male  80.0             0              1          Yes        Private   
2     Female  49.0             0              0          Yes        Private   
3     Female  79.0             1              0          Yes  Self-employed   
4       Male  81.0             0              0          Yes        Private   
...      ...   ...           ...            ...          ...            ...   
4976    Male  41.0             0              0           No        Private   
4977    Male  40.0             0              0          Yes        Private   
4978  Female  45.0             1              0          Yes       Govt_job   
4979    Male  40.0             0              0          Yes        Private   
4980  Female  80.0             1              0          Yes        Private   

     Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
0             Urban             228.69  36.6  formerly smoked       1  
1             Rural             105.92  32.5     never smoked       1  
2             Urban             171.23  34.4           smokes       1  
3             Rural             174.12  24.0     never smoked       1  
4             Urban             186.21  29.0  formerly smoked       1  
...             ...                ...   ...              ...     ...  
4976          Rural              70.15  29.8  formerly smoked       0  
4977          Urban             191.15  31.1           smokes       0  
4978          Rural              95.02  31.8           smokes       0  
4979          Rural              83.94  30.0           smokes       0  
4980          Urban              83.75  29.1     never smoked       0  

[4981 rows x 11 columns]

In [559]:
# Drop columns 4, 5, 6 and 9
df=df.drop(columns=df.columns[[4,5,6,9]])

In [560]:
df

gender   age  hypertension  heart_disease  avg_glucose_level   bmi  \
0       Male  67.0             0              1             228.69  36.6   
1       Male  80.0             0              1             105.92  32.5   
2     Female  49.0             0              0             171.23  34.4   
3     Female  79.0             1              0             174.12  24.0   
4       Male  81.0             0              0             186.21  29.0   
...      ...   ...           ...            ...                ...   ...   
4976    Male  41.0             0              0              70.15  29.8   
4977    Male  40.0             0              0             191.15  31.1   
4978  Female  45.0             1              0              95.02  31.8   
4979    Male  40.0             0              0              83.94  30.0   
4980  Female  80.0             1              0              83.75  29.1   

      stroke  
0          1  
1          1  
2          1  
3          1  
4          1  
...      ...  
4976       0  
4977       0  
4978       0  
4979       0  
4980       0  

[4981 rows x 7 columns]

In [561]:
# we import new libraries to encode the Gender column
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder

In [562]:
label = LabelEncoder()
label

LabelEncoder()

In [563]:
# Performing Label Encoding for "Gender Column"
label.fit_transform(df.gender)
df['gender']=label.fit_transform(df.gender)
df.gender

0       1
1       1
2       0
3       0
4       1
       ..
4976    1
4977    1
4978    0
4979    1
4980    0
Name: gender, Length: 4981, dtype: int32

In [564]:
type(df['gender'])

pandas.core.series.Series

In [565]:
df

gender   age  hypertension  heart_disease  avg_glucose_level   bmi  \
0          1  67.0             0              1             228.69  36.6   
1          1  80.0             0              1             105.92  32.5   
2          0  49.0             0              0             171.23  34.4   
3          0  79.0             1              0             174.12  24.0   
4          1  81.0             0              0             186.21  29.0   
...      ...   ...           ...            ...                ...   ...   
4976       1  41.0             0              0              70.15  29.8   
4977       1  40.0             0              0             191.15  31.1   
4978       0  45.0             1              0              95.02  31.8   
4979       1  40.0             0              0              83.94  30.0   
4980       0  80.0             1              0              83.75  29.1   

      stroke  
0          1  
1          1  
2          1  
3          1  
4          1  
...      ...  
4976       0  
4977       0  
4978       0  
4979       0  
4980       0  

[4981 rows x 7 columns]

In [566]:
# create input data as x and create output data as y
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [631]:
x.shape

(4981, 6)

In [633]:
y

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [569]:
# import additionl required libraries
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score, classification_report
print("importing is done")

importing is done


In [613]:
# now we create training and testing data for our model
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2,random_state=70)

In [636]:
# now we check our testing and training variables
x_train

array([[ 1.  , 55.  ,  0.  ,  0.  , 97.4 , 44.6 ],
       [ 1.  , 49.  ,  0.  ,  0.  , 70.73, 27.3 ],
       [ 1.  , 43.  ,  0.  ,  0.  , 56.08, 23.9 ],
       ...,
       [ 0.  ,  2.  ,  0.  ,  0.  , 65.96, 19.7 ],
       [ 0.  , 81.  ,  1.  ,  1.  , 59.11, 20.7 ],
       [ 1.  , 57.  ,  0.  ,  0.  , 75.53, 33.1 ]])

In [635]:
x_test

array([[  0.  ,  65.  ,   0.  ,   0.  , 248.24,  27.  ],
       [  1.  ,  55.  ,   0.  ,   0.  , 231.15,  22.3 ],
       [  0.  ,  26.  ,   0.  ,   0.  , 136.1 ,  26.4 ],
       ...,
       [  0.  ,  11.  ,   0.  ,   0.  , 122.75,  14.3 ],
       [  0.  ,  66.  ,   0.  ,   0.  , 200.91,  27.6 ],
       [  0.  ,   2.  ,   0.  ,   0.  , 102.92,  17.6 ]])

In [637]:
y_train

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [638]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [575]:
#create a model
model_k = AdaBoostClassifier()
model_k

AdaBoostClassifier()

In [576]:
# we train our model
model_k.fit(x_train, y_train)

AdaBoostClassifier()

In [577]:
# Now testing new Model prediction by providing Test Data set
y_k=model_k.predict(x_test)

In [578]:
# this is our variable which has learned the test data
y_k

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [579]:
# to check accuracy we need to import additional library
from sklearn.metrics import accuracy_score, classification_report

In [580]:
# Compare predictions with testing data given
# this will only give accuracy
accuracy = accuracy_score(y_test, y_k)
np.round(accuracy,2)*100

96.0

In [581]:
# Generate a detailed classification report
report = classification_report(y_test, y_k)
print(report)

              precision    recall  f1-score   support

           0       0.96      1.00      0.98       958
           1       1.00      0.03      0.05        39

    accuracy                           0.96       997
   macro avg       0.98      0.51      0.52       997
weighted avg       0.96      0.96      0.94       997



In [582]:
# we get 96% accuracy by keeping split as 80/20.
# if we keep split as 70/30
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.3,random_state=70)
model_k = AdaBoostClassifier()
model_k.fit(x_train, y_train)
y_k=model_k.predict(x_test)
accuracy = accuracy_score(y_test, y_k)
np.round(accuracy,2)*100

96.0

In [583]:
# we get 96% accuracy by keeping split as 70/30.
# if we keep split as 67/33
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.33,random_state=70)
model_k = AdaBoostClassifier()
model_k.fit(x_train, y_train)
y_k=model_k.predict(x_test)
accuracy = accuracy_score(y_test, y_k)
np.round(accuracy,2)*100

96.0

In [620]:
# Predicting the output of single test data using our trained model
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [630]:
x_test[0]

array([  0.  ,  65.  ,   0.  ,   0.  , 248.24,  27.  ])

In [639]:
model_k.predict(x_test[0])
#we get error here because x test is only 1 dimensional, we have to make it 2 dimensional to a prediction,  so we do reshape as shown in next cells.

ValueError: Expected 2D array, got 1D array instead:
array=[  0.    65.     0.     0.   248.24  27.  ].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [623]:
x_test[0].shape

(6,)

In [624]:
x_test[0].reshape(1,6)

array([[  0.  ,  65.  ,   0.  ,   0.  , 248.24,  27.  ]])

In [626]:
x_test[0].reshape(1,6).shape

(1, 6)

In [640]:
model_k.predict(x_test[0].reshape(1,6))

array([0], dtype=int64)

In [ ]:
# conclusion: Thus the model is able to predict correctly.