In [27]:
# import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print("importing is done")

importing is done


In [28]:
#load the dataset
df=pd.read_csv('brain_stroke.csv')

In [29]:
#summarizing the dataset
df

gender   age  hypertension  heart_disease ever_married      work_type  \
0       Male  67.0             0              1          Yes        Private   
1       Male  80.0             0              1          Yes        Private   
2     Female  49.0             0              0          Yes        Private   
3     Female  79.0             1              0          Yes  Self-employed   
4       Male  81.0             0              0          Yes        Private   
...      ...   ...           ...            ...          ...            ...   
4976    Male  41.0             0              0           No        Private   
4977    Male  40.0             0              0          Yes        Private   
4978  Female  45.0             1              0          Yes       Govt_job   
4979    Male  40.0             0              0          Yes        Private   
4980  Female  80.0             1              0          Yes        Private   

     Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
0             Urban             228.69  36.6  formerly smoked       1  
1             Rural             105.92  32.5     never smoked       1  
2             Urban             171.23  34.4           smokes       1  
3             Rural             174.12  24.0     never smoked       1  
4             Urban             186.21  29.0  formerly smoked       1  
...             ...                ...   ...              ...     ...  
4976          Rural              70.15  29.8  formerly smoked       0  
4977          Urban             191.15  31.1           smokes       0  
4978          Rural              95.02  31.8           smokes       0  
4979          Rural              83.94  30.0           smokes       0  
4980          Urban              83.75  29.1     never smoked       0  

[4981 rows x 11 columns]

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4981 entries, 0 to 4980
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   gender             4981 non-null   object 
 1   age                4981 non-null   float64
 2   hypertension       4981 non-null   int64  
 3   heart_disease      4981 non-null   int64  
 4   ever_married       4981 non-null   object 
 5   work_type          4981 non-null   object 
 6   Residence_type     4981 non-null   object 
 7   avg_glucose_level  4981 non-null   float64
 8   bmi                4981 non-null   float64
 9   smoking_status     4981 non-null   object 
 10  stroke             4981 non-null   int64  
dtypes: float64(3), int64(3), object(5)
memory usage: 428.2+ KB


In [31]:
df.dtypes

gender                object
age                  float64
hypertension           int64
heart_disease          int64
ever_married          object
work_type             object
Residence_type        object
avg_glucose_level    float64
bmi                  float64
smoking_status        object
stroke                 int64
dtype: object

In [32]:
df.describe()

age  hypertension  heart_disease  avg_glucose_level  \
count  4981.000000   4981.000000    4981.000000        4981.000000   
mean     43.419859      0.096165       0.055210         105.943562   
std      22.662755      0.294848       0.228412          45.075373   
min       0.080000      0.000000       0.000000          55.120000   
25%      25.000000      0.000000       0.000000          77.230000   
50%      45.000000      0.000000       0.000000          91.850000   
75%      61.000000      0.000000       0.000000         113.860000   
max      82.000000      1.000000       1.000000         271.740000   

               bmi       stroke  
count  4981.000000  4981.000000  
mean     28.498173     0.049789  
std       6.790464     0.217531  
min      14.000000     0.000000  
25%      23.700000     0.000000  
50%      28.100000     0.000000  
75%      32.600000     0.000000  
max      48.900000     1.000000

In [33]:
# pre-processing the dataset
# Now we check if any Null value is present or not 
df.isnull().sum()

gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

In [34]:
# we use max fucntion to find null values
df.isnull().sum().max()

0

In [35]:
df

gender   age  hypertension  heart_disease ever_married      work_type  \
0       Male  67.0             0              1          Yes        Private   
1       Male  80.0             0              1          Yes        Private   
2     Female  49.0             0              0          Yes        Private   
3     Female  79.0             1              0          Yes  Self-employed   
4       Male  81.0             0              0          Yes        Private   
...      ...   ...           ...            ...          ...            ...   
4976    Male  41.0             0              0           No        Private   
4977    Male  40.0             0              0          Yes        Private   
4978  Female  45.0             1              0          Yes       Govt_job   
4979    Male  40.0             0              0          Yes        Private   
4980  Female  80.0             1              0          Yes        Private   

     Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
0             Urban             228.69  36.6  formerly smoked       1  
1             Rural             105.92  32.5     never smoked       1  
2             Urban             171.23  34.4           smokes       1  
3             Rural             174.12  24.0     never smoked       1  
4             Urban             186.21  29.0  formerly smoked       1  
...             ...                ...   ...              ...     ...  
4976          Rural              70.15  29.8  formerly smoked       0  
4977          Urban             191.15  31.1           smokes       0  
4978          Rural              95.02  31.8           smokes       0  
4979          Rural              83.94  30.0           smokes       0  
4980          Urban              83.75  29.1     never smoked       0  

[4981 rows x 11 columns]

In [36]:
# we import new libraries to encode the Gender column
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder

In [37]:
label = LabelEncoder()
label

LabelEncoder()

In [38]:
# Performing Label Encoding for "Gender Column"
label.fit_transform(df.gender)
df['gender']=label.fit_transform(df.gender)
df.gender

0       1
1       1
2       0
3       0
4       1
       ..
4976    1
4977    1
4978    0
4979    1
4980    0
Name: gender, Length: 4981, dtype: int32

In [39]:
type(df['gender'])

pandas.core.series.Series

In [40]:
df

gender   age  hypertension  heart_disease ever_married      work_type  \
0          1  67.0             0              1          Yes        Private   
1          1  80.0             0              1          Yes        Private   
2          0  49.0             0              0          Yes        Private   
3          0  79.0             1              0          Yes  Self-employed   
4          1  81.0             0              0          Yes        Private   
...      ...   ...           ...            ...          ...            ...   
4976       1  41.0             0              0           No        Private   
4977       1  40.0             0              0          Yes        Private   
4978       0  45.0             1              0          Yes       Govt_job   
4979       1  40.0             0              0          Yes        Private   
4980       0  80.0             1              0          Yes        Private   

     Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
0             Urban             228.69  36.6  formerly smoked       1  
1             Rural             105.92  32.5     never smoked       1  
2             Urban             171.23  34.4           smokes       1  
3             Rural             174.12  24.0     never smoked       1  
4             Urban             186.21  29.0  formerly smoked       1  
...             ...                ...   ...              ...     ...  
4976          Rural              70.15  29.8  formerly smoked       0  
4977          Urban             191.15  31.1           smokes       0  
4978          Rural              95.02  31.8           smokes       0  
4979          Rural              83.94  30.0           smokes       0  
4980          Urban              83.75  29.1     never smoked       0  

[4981 rows x 11 columns]

In [41]:
# Performing Label Encoding for "ever_married Column"
label.fit_transform(df.ever_married)
df['ever_married']=label.fit_transform(df.ever_married)
df.ever_married

0       1
1       1
2       1
3       1
4       1
       ..
4976    0
4977    1
4978    1
4979    1
4980    1
Name: ever_married, Length: 4981, dtype: int32

In [42]:
type(df['ever_married'])

pandas.core.series.Series

In [43]:
df

gender   age  hypertension  heart_disease  ever_married      work_type  \
0          1  67.0             0              1             1        Private   
1          1  80.0             0              1             1        Private   
2          0  49.0             0              0             1        Private   
3          0  79.0             1              0             1  Self-employed   
4          1  81.0             0              0             1        Private   
...      ...   ...           ...            ...           ...            ...   
4976       1  41.0             0              0             0        Private   
4977       1  40.0             0              0             1        Private   
4978       0  45.0             1              0             1       Govt_job   
4979       1  40.0             0              0             1        Private   
4980       0  80.0             1              0             1        Private   

     Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
0             Urban             228.69  36.6  formerly smoked       1  
1             Rural             105.92  32.5     never smoked       1  
2             Urban             171.23  34.4           smokes       1  
3             Rural             174.12  24.0     never smoked       1  
4             Urban             186.21  29.0  formerly smoked       1  
...             ...                ...   ...              ...     ...  
4976          Rural              70.15  29.8  formerly smoked       0  
4977          Urban             191.15  31.1           smokes       0  
4978          Rural              95.02  31.8           smokes       0  
4979          Rural              83.94  30.0           smokes       0  
4980          Urban              83.75  29.1     never smoked       0  

[4981 rows x 11 columns]

In [44]:
# Performing Label Encoding for "work_type Column"
label.fit_transform(df.work_type)
df['work_type']=label.fit_transform(df.work_type)
df.work_type

0       1
1       1
2       1
3       2
4       1
       ..
4976    1
4977    1
4978    0
4979    1
4980    1
Name: work_type, Length: 4981, dtype: int32

In [45]:
type(df['work_type'])

pandas.core.series.Series

In [46]:
df

gender   age  hypertension  heart_disease  ever_married  work_type  \
0          1  67.0             0              1             1          1   
1          1  80.0             0              1             1          1   
2          0  49.0             0              0             1          1   
3          0  79.0             1              0             1          2   
4          1  81.0             0              0             1          1   
...      ...   ...           ...            ...           ...        ...   
4976       1  41.0             0              0             0          1   
4977       1  40.0             0              0             1          1   
4978       0  45.0             1              0             1          0   
4979       1  40.0             0              0             1          1   
4980       0  80.0             1              0             1          1   

     Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
0             Urban             228.69  36.6  formerly smoked       1  
1             Rural             105.92  32.5     never smoked       1  
2             Urban             171.23  34.4           smokes       1  
3             Rural             174.12  24.0     never smoked       1  
4             Urban             186.21  29.0  formerly smoked       1  
...             ...                ...   ...              ...     ...  
4976          Rural              70.15  29.8  formerly smoked       0  
4977          Urban             191.15  31.1           smokes       0  
4978          Rural              95.02  31.8           smokes       0  
4979          Rural              83.94  30.0           smokes       0  
4980          Urban              83.75  29.1     never smoked       0  

[4981 rows x 11 columns]

In [47]:
# Performing Label Encoding for "Residence_type Column"
label.fit_transform(df.Residence_type)
df['Residence_type']=label.fit_transform(df.Residence_type)
df.Residence_type

0       1
1       0
2       1
3       0
4       1
       ..
4976    0
4977    1
4978    0
4979    0
4980    1
Name: Residence_type, Length: 4981, dtype: int32

In [48]:
type(df['Residence_type'])

pandas.core.series.Series

In [49]:
df

gender   age  hypertension  heart_disease  ever_married  work_type  \
0          1  67.0             0              1             1          1   
1          1  80.0             0              1             1          1   
2          0  49.0             0              0             1          1   
3          0  79.0             1              0             1          2   
4          1  81.0             0              0             1          1   
...      ...   ...           ...            ...           ...        ...   
4976       1  41.0             0              0             0          1   
4977       1  40.0             0              0             1          1   
4978       0  45.0             1              0             1          0   
4979       1  40.0             0              0             1          1   
4980       0  80.0             1              0             1          1   

      Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
0                  1             228.69  36.6  formerly smoked       1  
1                  0             105.92  32.5     never smoked       1  
2                  1             171.23  34.4           smokes       1  
3                  0             174.12  24.0     never smoked       1  
4                  1             186.21  29.0  formerly smoked       1  
...              ...                ...   ...              ...     ...  
4976               0              70.15  29.8  formerly smoked       0  
4977               1             191.15  31.1           smokes       0  
4978               0              95.02  31.8           smokes       0  
4979               0              83.94  30.0           smokes       0  
4980               1              83.75  29.1     never smoked       0  

[4981 rows x 11 columns]

In [50]:
# Performing Label Encoding for "smoking_status Column"
label.fit_transform(df.smoking_status)
df['smoking_status']=label.fit_transform(df.smoking_status)
df.smoking_status

0       1
1       2
2       3
3       2
4       1
       ..
4976    1
4977    3
4978    3
4979    3
4980    2
Name: smoking_status, Length: 4981, dtype: int32

In [51]:
type(df['smoking_status'])

pandas.core.series.Series

In [52]:
df

gender   age  hypertension  heart_disease  ever_married  work_type  \
0          1  67.0             0              1             1          1   
1          1  80.0             0              1             1          1   
2          0  49.0             0              0             1          1   
3          0  79.0             1              0             1          2   
4          1  81.0             0              0             1          1   
...      ...   ...           ...            ...           ...        ...   
4976       1  41.0             0              0             0          1   
4977       1  40.0             0              0             1          1   
4978       0  45.0             1              0             1          0   
4979       1  40.0             0              0             1          1   
4980       0  80.0             1              0             1          1   

      Residence_type  avg_glucose_level   bmi  smoking_status  stroke  
0                  1             228.69  36.6               1       1  
1                  0             105.92  32.5               2       1  
2                  1             171.23  34.4               3       1  
3                  0             174.12  24.0               2       1  
4                  1             186.21  29.0               1       1  
...              ...                ...   ...             ...     ...  
4976               0              70.15  29.8               1       0  
4977               1             191.15  31.1               3       0  
4978               0              95.02  31.8               3       0  
4979               0              83.94  30.0               3       0  
4980               1              83.75  29.1               2       0  

[4981 rows x 11 columns]

In [53]:
# create input data as x and create output data as y
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [54]:
x.shape

(4981, 10)

In [55]:
y

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [56]:
# import additionl required libraries
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score, classification_report
print("importing is done")

importing is done


In [57]:
# now we create training and testing data for our model
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2,random_state=70)

In [58]:
# now we check our testing and training variables
x_train

array([[ 1.  , 55.  ,  0.  , ..., 97.4 , 44.6 ,  1.  ],
       [ 1.  , 49.  ,  0.  , ..., 70.73, 27.3 ,  1.  ],
       [ 1.  , 43.  ,  0.  , ..., 56.08, 23.9 ,  0.  ],
       ...,
       [ 0.  ,  2.  ,  0.  , ..., 65.96, 19.7 ,  0.  ],
       [ 0.  , 81.  ,  1.  , ..., 59.11, 20.7 ,  1.  ],
       [ 1.  , 57.  ,  0.  , ..., 75.53, 33.1 ,  1.  ]])

In [59]:
x_test

array([[  0.  ,  65.  ,   0.  , ..., 248.24,  27.  ,   3.  ],
       [  1.  ,  55.  ,   0.  , ..., 231.15,  22.3 ,   2.  ],
       [  0.  ,  26.  ,   0.  , ..., 136.1 ,  26.4 ,   0.  ],
       ...,
       [  0.  ,  11.  ,   0.  , ..., 122.75,  14.3 ,   0.  ],
       [  0.  ,  66.  ,   0.  , ..., 200.91,  27.6 ,   2.  ],
       [  0.  ,   2.  ,   0.  , ..., 102.92,  17.6 ,   0.  ]])

In [60]:
y_train

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [61]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [62]:
#create a model
model_k = AdaBoostClassifier()
model_k

AdaBoostClassifier()

In [63]:
# we train our model
model_k.fit(x_train, y_train)

AdaBoostClassifier()

In [65]:
# Now testing new Model prediction by providing Test Data set
y_k=model_k.predict(x_test)

In [66]:
# this is our variable which has learned the test data
y_k

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [67]:
# to check accuracy we need to import additional library
from sklearn.metrics import accuracy_score, classification_report

In [68]:
# Compare predictions with testing data given
# this will only give accuracy
accuracy = accuracy_score(y_test, y_k)
np.round(accuracy,2)*100

96.0

In [69]:
# Generate a detailed classification report
report = classification_report(y_test, y_k)
print(report)

              precision    recall  f1-score   support

           0       0.96      1.00      0.98       958
           1       1.00      0.03      0.05        39

    accuracy                           0.96       997
   macro avg       0.98      0.51      0.52       997
weighted avg       0.96      0.96      0.94       997



In [70]:
# we get 96% accuracy by keeping split as 80/20.
# if we keep split as 70/30
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.3,random_state=70)
model_k = AdaBoostClassifier()
model_k.fit(x_train, y_train)
y_k=model_k.predict(x_test)
accuracy = accuracy_score(y_test, y_k)
np.round(accuracy,2)*100

96.0

In [71]:
# we get 96% accuracy by keeping split as 70/30.
# if we keep split as 67/33
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.33,random_state=70)
model_k = AdaBoostClassifier()
model_k.fit(x_train, y_train)
y_k=model_k.predict(x_test)
accuracy = accuracy_score(y_test, y_k)
np.round(accuracy,2)*100

96.0

In [72]:
# Predicting the output of single test data using our trained model
y_test

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [73]:
x_test[0]

array([  0.  ,  65.  ,   0.  ,   0.  ,   1.  ,   2.  ,   1.  , 248.24,
        27.  ,   3.  ])

In [74]:
model_k.predict(x_test[0])
#we get error here because x test is only 1 dimensional, we have to make it 2 dimensional to a prediction,  so we do reshape as shown in next cells.

ValueError: Expected 2D array, got 1D array instead:
array=[  0.    65.     0.     0.     1.     2.     1.   248.24  27.     3.  ].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [80]:
x_test[0].shape

(10,)

In [81]:
x_test[0].reshape(1,10)

array([[  0.  ,  65.  ,   0.  ,   0.  ,   1.  ,   2.  ,   1.  , 248.24,
         27.  ,   3.  ]])

In [82]:
x_test[0].reshape(1,10).shape

(1, 10)

In [83]:
model_k.predict(x_test[0].reshape(1,10))

array([0], dtype=int64)

In [79]:
# conclusion: Thus the model is able to predict correctly.